services:
  # mongodb:
  #   image: prismagraphql/mongo-single-replica:4.4.3-bionic
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: prisma
  #     INIT_WAIT_SEC: 3
  #   command: ["--bind_ip_all", "--quiet"]
  #   networks:
  #     - backend
  # nginx:
  #   hostname: nginx
  #   restart: always
  #   build:
  #     context: "./nginx"
  #   volumes:
  #     - ./nginx/conf.d/:/etc/nginx/conf.d/
  #     - ./nginx/log:/var/log/nginx/
  #   ports:
  #     - "443:443"
  #     - "80:80"
  #   networks:
  #     - backend

  # backend:
  #   hostname: backend
  #   restart: always
  #   command: pnpm -F backend run dev
  #   environment:
  #     DATABASE_URL: mongodb://root:prisma@mongodb:27017/test?authSource=admin&retryWrites=true&w=majority&directConnection=true
  #     PORT: "8080"
  #   volumes:
  #     - ./:/app
  #   build:
  #     dockerfile: ./backend.Dockerfile
  #   networks:
  #     - backend

  # chatbot:
  #   hostname: chatbot
  #   restart: always
  #   volumes:
  #     - ./packages/chatbot/:/app
  #   command: python main.py
  #   environment:
  #     PORT: "5000"
  #   # ports:
  #   #   - "5000:5000"
  #   build:
  #     context: "./packages/chatbot"
  #   networks:
  #     - backend

  backend-go:
    hostname: backend-go
    restart: always
    volumes:
      - ./packages/backend-go-concurrency/:/app
    command: air
    ports:
      - "5500:5500"
    environment:
      PORT: "5500"
      DATABASE_URL: mongodb://root:prisma@mongodb:27017/test?authSource=admin&retryWrites=true&w=majority&directConnection=true
    build:
      context: "./packages/backend-go-concurrency"
    networks:
      - backend

networks:
  backend:
    name: backend
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.123.0/24
